from Admin import *
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BusBookingSystem(object):

    def setupUi(self, BusBookingSystem):
        BusBookingSystem.setObjectName("BusBookingSystem")
        BusBookingSystem.resize(800, 600)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        BusBookingSystem.setPalette(palette)
        BusBookingSystem.setToolTipDuration(0)


        self.centralwidget = QtWidgets.QWidget(BusBookingSystem)
        self.centralwidget.setObjectName("centralwidget")


        self.Input_User = QtWidgets.QLineEdit(self.centralwidget,
                                              placeholderText='نام کاربری خود را وارد کنید...')
        self.Input_User.setGeometry(QtCore.QRect(450, 160, 170, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHeightForWidth(self.Input_User.sizePolicy().hasHeightForWidth())
        self.Input_User.setSizePolicy(sizePolicy)
        self.Input_User.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.Input_User.setObjectName("Input_User")


        self.Username = QtWidgets.QLabel(self.centralwidget)
        self.Username.setGeometry(QtCore.QRect(580, 160, 150, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        self.Username.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Peyda")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Username.setFont(font)
        self.Username.setObjectName("Username")


        self.Input_Pass = QtWidgets.QLineEdit(self.centralwidget,
                                              placeholderText='کلمه عبور خود را وارد کنید...')
        self.Input_Pass.setGeometry(QtCore.QRect(450, 210, 170, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHeightForWidth(self.Input_Pass.sizePolicy().hasHeightForWidth())
        self.Input_Pass.setSizePolicy(sizePolicy)
        self.Input_Pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Input_Pass.setClearButtonEnabled(True)
        self.Input_Pass.setObjectName("Input_Pass")


        self.Password = QtWidgets.QLabel(self.centralwidget)
        self.Password.setGeometry(QtCore.QRect(580, 210, 150, 20))
        self.Password.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Peyda")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Password.setFont(font)
        self.Password.setObjectName("Password")


        self.Login_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Login_Button.setEnabled(True)
        self.Login_Button.setGeometry(QtCore.QRect(450, 290, 280, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        self.Login_Button.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Peyda Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.Login_Button.setFont(font)
        self.Login_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Login_Button.setToolTipDuration(-1)
        self.Login_Button.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Login_Button.setAutoFillBackground(True)
        self.Login_Button.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        self.Login_Button.setIconSize(QtCore.QSize(16, 16))
        self.Login_Button.setFlat(True)
        self.Login_Button.setObjectName("Login_Button")


        self.Cancel_Ticket = QtWidgets.QPushButton(self.centralwidget)
        self.Cancel_Ticket.setGeometry(QtCore.QRect(0, 30, 200, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        self.Cancel_Ticket.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Kalameh Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.Cancel_Ticket.setFont(font)
        self.Cancel_Ticket.setAutoFillBackground(True)
        self.Cancel_Ticket.setFlat(True)
        self.Cancel_Ticket.setObjectName("Cancel_Ticket")


        self.inquiry = QtWidgets.QPushButton(self.centralwidget)
        self.inquiry.setGeometry(QtCore.QRect(200, 30, 200, 50))
        self.inquiry.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Kalameh Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.inquiry.setFont(font)
        self.inquiry.setAutoFillBackground(True)
        self.inquiry.setFlat(True)
        self.inquiry.setObjectName("inquiry")


        self.buy_ticket = QtWidgets.QPushButton(self.centralwidget)
        self.buy_ticket.setGeometry(QtCore.QRect(400, 30, 200, 50))
        self.buy_ticket.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Kalameh Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.buy_ticket.setFont(font)
        self.buy_ticket.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.buy_ticket.setAutoFillBackground(True)
        self.buy_ticket.setInputMethodHints(QtCore.Qt.ImhNone)
        self.buy_ticket.setFlat(True)
        self.buy_ticket.setObjectName("buy_ticket")


        self.Nav_White = QtWidgets.QPushButton(self.centralwidget)
        self.Nav_White.setEnabled(False)
        self.Nav_White.setGeometry(QtCore.QRect(0, 30, 800, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.Nav_White.setPalette(palette)
        self.Nav_White.setAutoFillBackground(True)
        self.Nav_White.setFlat(True)
        self.Nav_White.setObjectName("Nav_White")


        self.Nav_Blue = QtWidgets.QPushButton(self.centralwidget)
        self.Nav_Blue.setEnabled(False)
        self.Nav_Blue.setGeometry(QtCore.QRect(0, 0, 800, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.Nav_Blue.setPalette(palette)
        self.Nav_Blue.setAutoFillBackground(True)
        self.Nav_Blue.setFlat(True)
        self.Nav_Blue.setObjectName("Nav_Blue")


        self.Sign_up = QtWidgets.QPushButton(self.centralwidget)
        self.Sign_up.setGeometry(QtCore.QRect(80, 0, 70, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        self.Sign_up.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Anjoman")
        font.setPointSize(12)
        self.Sign_up.setFont(font)
        self.Sign_up.setFlat(True)
        self.Sign_up.setObjectName("Sign_up")


        self.Log_in = QtWidgets.QPushButton(self.centralwidget)
        self.Log_in.setGeometry(QtCore.QRect(20, 0, 50, 30))
        self.Log_in.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Anjoman")
        font.setPointSize(12)
        self.Log_in.setFont(font)
        self.Log_in.setFlat(True)
        self.Log_in.setObjectName("Log_in")


        self.lineSL = QtWidgets.QPushButton(self.centralwidget)
        self.lineSL.setEnabled(False)
        self.lineSL.setGeometry(QtCore.QRect(70, 0, 15, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.lineSL.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Anjoman")
        font.setPointSize(12)
        self.lineSL.setFont(font)
        self.lineSL.setFlat(True)
        self.lineSL.setObjectName("lineSL")


        self.Call_us = QtWidgets.QLabel(self.centralwidget)
        self.Call_us.setGeometry(QtCore.QRect(520, 0, 250, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        self.Call_us.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("IRANYekanFN Medium")
        font.setPointSize(10)
        self.Call_us.setFont(font)
        self.Call_us.setObjectName("Call_us")


        self.Background = QtWidgets.QLabel(self.centralwidget)
        self.Background.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.Background.setPixmap(QtGui.QPixmap("REQUIRMENTS/000ntitled-1.jpg"))
        self.Background.setObjectName("Background")


        self.Black_back = QtWidgets.QPushButton(self.centralwidget)
        self.Black_back.setEnabled(False)
        self.Black_back.setGeometry(QtCore.QRect(430, 130, 321, 240))
        self.Black_back.setAutoFillBackground(True)
        self.Black_back.setFlat(True)
        self.Black_back.setObjectName("Black_back")


        self.Logo = QtWidgets.QLabel(self.centralwidget)
        self.Logo.setGeometry(QtCore.QRect(670, 30, 100, 50))
        self.Logo.setPixmap(QtGui.QPixmap("REQUIRMENTS/logo.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setObjectName("Logo")



        self.Background.raise_()
        self.Black_back.raise_()
        self.Nav_Blue.raise_()
        self.Nav_White.raise_()
        self.Input_User.raise_()
        self.Username.raise_()
        self.Input_Pass.raise_()
        self.Password.raise_()
        self.Login_Button.raise_()
        self.Cancel_Ticket.raise_()
        self.inquiry.raise_()
        self.buy_ticket.raise_()
        self.Sign_up.raise_()
        self.Log_in.raise_()
        self.lineSL.raise_()
        self.Call_us.raise_()
        self.Logo.raise_()


        BusBookingSystem.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BusBookingSystem)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        self.menusafar725 = QtWidgets.QMenu(self.menubar)
        self.menusafar725.setObjectName("menusafar725")
        BusBookingSystem.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BusBookingSystem)
        self.statusbar.setObjectName("statusbar")
        BusBookingSystem.setStatusBar(self.statusbar)
        self.Closing = QtWidgets.QAction(BusBookingSystem)
        self.Closing.setObjectName("Closing")
        self.menusafar725.addAction(self.Closing)
        self.menusafar725.addSeparator()
        self.menusafar725.addSeparator()
        self.menubar.addAction(self.menusafar725.menuAction())


        self.retranslateUi(BusBookingSystem)
        QtCore.QMetaObject.connectSlotsByName(BusBookingSystem)


    def retranslateUi(self, BusBookingSystem):
        _translate = QtCore.QCoreApplication.translate
        BusBookingSystem.setWindowTitle(_translate("BusBookingSystem", "Bus Booking System"))
        self.Username.setText(_translate("BusBookingSystem", "نام کاربری:"))
        self.Password.setText(_translate("BusBookingSystem", "کلمـه‌ عبـور:"))
        self.Login_Button.setText(_translate("BusBookingSystem", "ورود"))
        self.Cancel_Ticket.setText(_translate("BusBookingSystem", "کنسلی بلیط"))
        self.inquiry.setText(_translate("BusBookingSystem", "استعلام بلیط"))
        self.buy_ticket.setText(_translate("BusBookingSystem", "خرید بلیط"))
        self.Sign_up.setText(_translate("BusBookingSystem", "ثبت نام"))
        self.Log_in.setText(_translate("BusBookingSystem", "ورود"))
        self.lineSL.setText(_translate("BusBookingSystem", "|"))
        self.Call_us.setText(_translate("BusBookingSystem", "پشتیبانی و فروش 53826-021"))
        self.menusafar725.setTitle(_translate("BusBookingSystem", "صفحه اصلی"))
        self.Closing.setText(_translate("BusBookingSystem", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BusBookingSystem = QtWidgets.QMainWindow()
    ui = Ui_BusBookingSystem()
    ui.setupUi(BusBookingSystem)
    BusBookingSystem.show()
    sys.exit(app.exec_())